name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: npm ci
      - run: npm run build
        env:
          SPEECHLY_APP_ID: ${{ secrets.SPEECHLY_APP_ID }}
          SPEECHLY_APP_LANG: ${{ secrets.SPEECHLY_APP_LANG }}
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
